  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: argocd-notifications-cm
  data:
    service.slack: |
      token: $slack-token

    context: |
      argocdUrl: http://localhost:8080

    template.app-sync-succeeded: |
      message: |
        Application {{.app.metadata.name}} is now running the new version of its manifests.
      slack:
        attachments: |
          [{
            "title": "{{.app.metadata.name}}",
            "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#18be52",
            "fields": [{"title": "Sync Status", "value": "{{.app.status.sync.status}}", "short": true}]
          }]
  
    template.app-sync-failed: |
      message: |
        The sync of {{.app.metadata.name}} failed: {{.app.status.operationState.message}}
      slack:
        attachments: |
          [{
            "title": "{{.app.metadata.name}}",
            "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "fields": [{"title": "Sync Status", "value": "{{.app.status.sync.status}}", "short": true}]
          }]
  
    template.app-health-degraded: |
      message: |
        Application {{.app.metadata.name}} has degraded.
      slack:
        attachments: |
          [{
            "title": "{{.app.metadata.name}}",
            "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#ff0000",
            "fields": [{"title": "Health Status", "value": "{{.app.status.health.status}}", "short": true}]
          }]
  
    trigger.on-sync-succeeded: |
      - when: app.status.operationState.phase in ['Succeeded']
        send: [app-sync-succeeded]
  
    trigger.on-sync-failed: |
      - when: app.status.operationState.phase in ['Error', 'Failed']
        send: [app-sync-failed]
  
    trigger.on-health-degraded: |
      - when: app.status.health.status == 'Degraded'
        send: [app-health-degraded]

