apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
name: argocd-notifications-secret
namespace: argocd
spec:
secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
target: 
    name: argocd-notifications-secret
data:
    -   secretKey: slack-token
        remoteRef: 
            key: argocd-notifications/slack
            property: token
