replicaCount: 1

image:
  repository: docker.n8n.io/n8nio/n8n
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5678

persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce

env:
  N8N_HOST: "localhost"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "http"
  N8N_EDITOR_BASE_URL: "http://localhost:5678/"
  WEBHOOK_URL: "http://localhost:5678/"
  GENERIC_TIMEZONE: "Asia/Kolkata"

resources: {}
