apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lab-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - chartName: hello-world
            chartPath: charts/hello-world
  template:
    metadata:
      name: 'lab-{{chartName}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: lab
      destination:
        namespace: app
        server: https://kubernetes.default.svc
      sources:
        - repoURL: https://github.com/msaxena14/ArgoCD.git
          targetRevision: main
          path: '{{chartPath}}'
          helm:
            releaseName: 'lab-{{chartName}}'
            valueFiles:
              - $values/values/local/{{chartName}}/values.yaml
        - repoURL: https://github.com/msaxena14/ArgoCD.git
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
