apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lab
  namespace: argocd
spec:
  description: A sandbox lab project for testing ArgoCD configurations and applications.
  sourceRepos: 
      - https://github.com/msaxena14/ArgoCD.git
      - https://charts.external-secrets.io
  destinations:
    - namespace: 'app'
      server: https://kubernetes.default.svc
    - namespace: 'external-secrets'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
