apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.name" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello-world.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-world.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "hello-world.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MESSAGE
              value: {{ .Values.message | quote }}
          ports:
            - containerPort: 80
